app:
  name: Container Engine
  version: 1.0.0


spring:
  profiles:
    active: dev
  # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: -1


# 应用服务 WEB 访问端口
server:
  port: 8808

swagger:
  enabled: true


#docker配置
docker:
#  clientHost: localhost
#  server-host: 172.21.212.177
  server-host: localhost
  server-port: 2375
#  clientMac: 18-C0-4D-38-98-4B
#  useDockerHub: true
  registry-url: 172.21.212.177:8080



