app:
  name: Container Engine
  version: 1.0.0


spring:
  # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 应用服务 WEB 访问端口
server:
  port: 8808

swagger:
  enabled: true



